[[profile]]
name = "main"
    [[profile.output]]
    search = "HDMI-A-2"
    enable = true
    mode = "1920x1080@60Hz"
    position = "0,0"
    scale = 1
    transform = "90"

    [[profile.output]]
    search = "HDMI-A-1"
    enable = true
    position = "3640,0"
    transform = "90"
    mode = "1920x1080@60Hz"

    [[profile.output]]
    search = "DP-2"
    enable = true
    primary = true
    position = "1080,480"
    transform = "normal"
    mode = "2560x1440@120Hz"
